# NFL Players by Draft Position

In [28]:
import pandas as pd
import requests

In [29]:
url = 'http://www.drafthistory.com/index.php/years/2019'

In [42]:
request = requests.get(url)
d2019 = pd.read_html(r.text, header=1)
d2019 = d2019[0]
# d2019 = d2019.iloc[1:]
d2019

,Round,Pick,Player,Name,Team,Position,College
0,1.0,1,1,Kyler Murray,Cardinals,QB,Oklahoma
1,NaN,2,2,Nick Bosa,49ers,DE,Ohio State
2,NaN,3,3,Quinnen Williams,Jets,DT,Alabama
3,NaN,4,4,Clelin Ferrell,Raiders,DE,Clemson
4,NaN,5,5,Devin White,Buccaneers,LB,Louisiana State
...,...,...,...,...,...,...,...
249,NaN,36,250,Austin Cutting,Vikings,C,Air Force
250,NaN,37,251,Dakota Allen,Rams,LB,Texas Tech
251,NaN,38,252,Ken Webster,Patriots,DB,Mississippi
252,NaN,39,253,Jordan Brailford,Redskins,LB,Oklahoma State
253,NaN,40,254,Caleb Wilson,Cardinals,TE,UCLA

      2019 - Round 1                                                   \
              PLAYER POSITION      SCHOOL SEL #                  TEAM
0       Kyler Murray       QB    Oklahoma   1.0     Arizona Cardinals
1          Nick Bosa       DE  Ohio State   2.0   San Francisco 49ers
2   Quinnen Williams       DT     Alabama   3.0         New York Jets
3     Clelin Ferrell       DE     Clemson   4.0       Oakland Raiders
4        Devin White       LB         LSU   5.0  Tampa Bay Buccaneers
..               ...      ...         ...   ...                   ...
27               NaN      NaN         NaN   NaN                   NaN
28               NaN      NaN         NaN   NaN                   NaN
29               NaN      NaN         NaN   NaN                   NaN
30               NaN      NaN         NaN   NaN                   NaN
31               NaN      NaN         NaN   NaN                   NaN

    2019 - Round 2
            PLAYER POSITION         SCHOOL SEL #                  TEAM
0              NaN      NaN            NaN   NaN                   NaN
1              NaN      NaN            NaN   NaN                   NaN
2              NaN      NaN            NaN   NaN                   NaN
3              NaN      NaN            NaN   NaN                   NaN
4              NaN      NaN            NaN   NaN                   NaN
..             ...      ...            ...   ...                   ...
27  Nasir Adderley       DB       Delaware  60.0  Los Angeles Chargers
28     Taylor Rapp      SAF     Washington  61.0      Los Angeles Rams
29   Andy Isabella       WR  Massachusetts  62.0     Arizona Cardinals
30  Juan Thornhill       DB       Virginia  63.0    Kansas City Chiefs
31    D.K. Metcalf       WR    Mississippi  64.0      Seattle Seahawks

[64 rows x 10 columns]

In [17]:
draft2019